version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/src
    command: >
      sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # environment:
    #   - DB_HOST=db
    #   - DB_NAME=portfolioApp_development
    #   - DB_USER=postgres
    #   - DB_PASS=supersecretpassword
    #   - DB_PORT=5432
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=portfolioApp_develop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  mypostgresdb:
    external: true

