# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "unicorn_user"
      POSTGRES_PASSWORD: "magical_password"
      POSTGRES_DB: "portfolioApp_development"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local